spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema;DB_CLOSE_DELAY=-1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ujdyj100
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
